import puppeteer from "puppeteer";
const browser = await puppeteer.launch({ headless: "new", args: ["--no-sandbox", "--enable-unsafe-swiftshader"] });
const page = await browser.newPage();
await page.setViewport({ width: 1280, height: 720 });
await page.goto("http://localhost:8765/index.html", { waitUntil: "domcontentloaded" });
await page.waitForFunction("window.__sim", { timeout: 30000 });
for (let i = 0; i < 780; i++) await page.evaluate("window.__sim.step()");
const pose = await page.evaluate("window.__sim.getPose()");
console.log("final pose x", pose.x.toFixed(1), "y", pose.y.toFixed(1), "tick", pose.tick);
await new Promise(r => setTimeout(r, 200));
await page.screenshot({ path: "/tmp/sim_climbed.png" });
console.log("saved /tmp/sim_climbed.png");
await browser.close();
